# 公共配置
# 使得/refresh不需要验权
management:
  security:
    enabled: false

# jwt相关的配置
token:
  jwt:
    key: a123456789
    # 发放者
    iss: uaa-interface
    # 有效期120分钟
    expm: 120

spring:
  # rabbitmq的地址 用户名 密码
  rabbitmq:
    host: rabbitmq
    username: guest
    password: '{cipher}AQAdix9epTMkB7urDSSlSAE9g5j46S59ednXvfuwjFH8Zmw1MBmgZL/AarQq/VCyeGwRsB7b2jTlTQDasDYaFhUFeaRH79K52JjR3XV2NmzR1R8sjvd7w6apelb8Ryno1BWFrn5Uw59j0zzuVBlg/oEhv50o9zzBCIF0QER+Vdi5GQioIJSmvYi8OnrKR90vm7IkOK5sXvX3iocbLifm/yRi/SaeUTp6/EOqP1j9e4LE8WWEkNStfWdiT129JaFJ4N/WgkYhEHCNCbjrwdkvM8CIlcpPptUXo+wGE0QXiuVYYYhw01gJrW0PuehCEhByP6ehv+I3oAb+7PGEJzpGV4vkNsHltqbprik/w82iSOTHol+z0ivT7Y0ZnoAQu+2JpXM='
  sleuth:
    sampler:
      # 1、采样比例
      percentage: 1.0
  # 2、接口调用信息推送到这个zipkin服务
  zipkin: 
    base-url: http://zipkin:9411

  cloud:
    loadbalancer:
      # 开启重试
      retry:
        enabled: true
ribbon:
  # 配置ribbon超时时间
  ConnectTimeout: 5000
  ReadTimeout: 5000
  # 是否开启重试
  OkToRetryOnAllOperations: true
  # 重试期间，实例切换次数
  MaxAutoRetriesNextServer: 3
  # 当前实例重试次数
  MaxAutoRetries: 0

hystrix:
  threadpool:
    default:
      coreSize: 80
      maxQueueSize: 200
      queueSizeRejectionThreshold: 20
  command:
    # 这是默认的配置
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: THREAD
          thread:
            # 20秒超时
            timeoutInMilliseconds: 20000
      fallback:
        enabled: true
        isolation:
          semaphore:
            # 调用降级策略的并发量
            maxConcurrentRequests: 20
      circuitBreaker:
        enabled: true
        # 10秒内超过5个请求
        requestVolumeThreshold: 5
        # 错误率超过80，开启熔断
        errorThresholdPercentage: 80
        # 10秒后进入半开启
        sleepWindowInMilliseconds: 10000
      metrics:
        rollingStats:
          # 10秒统计一次
          timeInMilliseconds: 10000
          numBuckets: 10
